/* 관리자 사원 등록 테이블 생성 */

DROP TABLE ADMIN
CASCADE CONSTRAINT;

DROP SEQUENCE ADMIN_SEQ;

CREATE TABLE ADMIN(
	SEQ NUMBER(10) PRIMARY KEY,
	ID VARCHAR2(20) UNIQUE,
	PASSWORD VARCHAR2(20) NOT NULL,
	NAME VARCHAR2(20) NOT NULL,
	PHONE VARCHAR2(20) NOT NULL,
	STORE_SEQ NUMBER(10) NOT NULL,
	DEL NUMBER(1) NOT NULL
)

CREATE SEQUENCE ADMIN_SEQ
START WITH 1
INCREMENT BY 1;


INSERT INTO ADMIN(SEQ, ID, PASSWORD, NAME, PHONE, STORE_SEQ, DEL)
VALUES ( ADMIN_SEQ.NEXTVAL,'admin', 'admin', 'admin', '111-1111-1111', 1, 0 )


/* 지점 테이블 생성 */

DROP TABLE STORE
CASCADE CONSTRAINT;

DROP SEQUENCE STORE_SEQ;

CREATE TABLE STORE(
	SEQ NUMBER(10) PRIMARY KEY,
	NAME VARCHAR2(100) NOT NULL,
	PHONE VARCHAR2(20) NOT NULL,
	ADDRESS VARCHAR2(100) NOT NULL,
	LAT NUMBER(10) NOT NULL,
	LNG NUMBER(10) NOT NULL,
	DEL NUMBER(1) NOT NULL
)

CREATE SEQUENCE STORE_SEQ
START WITH 1
INCREMENT BY 1;

INSERT INTO STORE(SEQ, NAME, PHONE, ADDRESS, LAT, LNG, DEL)
VALUES ( STORE_SEQ.NEXTVAL,'A', '123-1234-1234', '서울시', 1, 1, 0 )

SELECT * FROM STORE;



ALTER TABLE ADMIN
ADD CONSTRAINT FK_STORE_SEQ FOREIGN KEY(STORE_SEQ)
REFERENCES STORE(SEQ);



